name: Main

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm ci --only=prod
      - run: npm build

  inspect:
    runs-on: ubuntu-latest
    steps:
      - run: npm ci --only=prod
      - run: npm inspect
