name: Main

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: npm ci
      - run: npm build

  inspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - run: npm ci
      - run: npm inspect
